version: '3.0'
services:
  redis-6381-boxes2:
    image: redis
    container_name: redis-6381-boxes2
    ports:
      - "6381:6381"
    volumes:
      - ./redis6381.conf:/etc/redis/redis.conf
    privileged: true
    command: redis-server /etc/redis/redis.conf
    
  sentinel-6381-boxes2:
    image: redis
    container_name: sentinel-6381-boxes2
    ports:
      - "26381:26381"
    volumes:
      - ./sentinel26381.conf:/etc/redis/sentinel.conf
    privileged: true
    command: redis-server /etc/redis/sentinel.conf --sentinel